version: '3'
services:
    fluentd:
        container_name: fluentd
        image: fluentd
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        user: fluent
        volumes:
            - ./config/etc:/fluentd/etc:ro
            - ./logs:/var/log/httpd:ro
        ports:
            - 24224:24224
            - 24224:24224/udp
