version: '3'
services:
    jaeger:
        container_name: jaeger
        image: jaegertracing/all-in-one
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        ports:
            # - 5775:5775/udp # zipkin.thrift over compact thrift protocol
            # - 6831:6831/udp # jaeger.thrift over compact thrift protocol
            # - 6832:6832/udp # jaeger.thrift over binary thrift protocol
            # - 5778:5778     # configs
            # - 9411:9411     # zipkin
            # - 14268:14268   # jaeger.thrift directly from clients
            - 16686:16686   # UI
            - 14250:14250   # gRPC
