receivers:
    otlp:
        protocols:
            grpc:
            http:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/simpleprometheusreceiver
    # prometheus_simple:
    #     collection_interval: 10s
    #     endpoint: 'host.docker.internal:8090'
    #     metrics_path: '/actuator/prometheus'
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver
    prometheus:
        config:
            global:
                scrape_interval: 10s
                evaluation_interval: 10s
            scrape_configs:
                # - job_name: 'webservices'
                #   metrics_path: '/actuator/prometheus'
                #   static_configs:
                #       - targets: [ 'host.docker.internal:8080' ]
                - job_name: 'eureka'
                  metrics_path: '/actuator/prometheus'
                  eureka_sd_configs:
                      - server: http://host.docker.internal:8761/eureka
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/zipkinreceiver
    zipkin:

processors:
    batch:
        timeout: 10s

exporters:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter
    prometheus:
        endpoint: '0.0.0.0:8889'
        send_timestamps: true
        metric_expiration: 180m
        enable_open_metrics: true
        resource_to_telemetry_conversion:
            enabled: true
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/zipkinexporter
    zipkin:
        endpoint: 'http://host.docker.internal:9412/api/v2/spans'
    logging:

extensions:
    health_check:
    pprof:
    zpages:

service:
    extensions: [pprof, zpages, health_check]
    pipelines:
        metrics:
            receivers: [otlp, prometheus]
            processors: [batch]
            exporters: [logging, prometheus]
        traces:
            receivers: [otlp, zipkin]
            processors: [batch]
            exporters: [logging, zipkin]
